# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cox_llk_cpp <- function(y, XData, beta, lambda, weight) {
    .Call(`_ELMCox_cox_llk_cpp`, y, XData, beta, lambda, weight)
}

cox_grad_cpp <- function(y, XData, beta, lambda, weight) {
    .Call(`_ELMCox_cox_grad_cpp`, y, XData, beta, lambda, weight)
}

cox_dgrad_cpp <- function(y, XData, beta, lambda, weight) {
    .Call(`_ELMCox_cox_dgrad_cpp`, y, XData, beta, lambda, weight)
}

mm_mult <- function(x, y) {
    .Call(`_ELMCox_mm_mult`, x, y)
}

testDFtoNM <- function(x) {
    .Call(`_ELMCox_testDFtoNM`, x)
}

scaleNM <- function(x1) {
    .Call(`_ELMCox_scaleNM`, x1)
}

kernmat <- function(xtrain, kernel_type, kernel_para, xtest) {
    .Call(`_ELMCox_kernmat`, xtrain, kernel_type, kernel_para, xtest)
}

